# Must be unique in a given SonarQube instance
sonar.projectKey=br.edu.fatec:minicurso-flask
sonar.projectName=Minicurso Flask
sonar.projectVersion=1.1

# Path is relative to this sonar-project.properties file.
sonar.sources=.

# Encoding of the source code.
sonar.sourceEncoding=UTF-8

# This SonarQube instance is exposed on host port 29000.
sonar.host.url=http://localhost:29000
